var translateEnglish={
  labels: {
    'navigation.contact':'Contact',
    'navigation.function':'Functions',
    'navigation.main':'Main Page',
    'header.welcome.title': 'With us you will always reach your destination',
    'header.welcome.button':'Find out more',
    'main.function.road': 'You know where you are traveling, but do not know how?',
    'main.function.road.alt': 'Plan your trip',
    'main.function.timetable': 'Check the lines and  timetables',
    'main.function.timetable.alt': 'Timetable',
    'main.function.busStop': 'You know which bus stop, you do not know which line you should take?',
    'main.function.busStop.alt': 'busStop',
    'main.function.delays' : 'Check the traffic situation',
    'main.function.delays.alt': 'traffic',
    'other.function.localization': 'Localization service',
    'other.function.localization.alt': 'localization service',
    'other.function.avoid':'Avoid transfers',
    'other.function.avoid.alt':'Avoid transfers',
    'other.function.traffic':'Situation on the road',
    'other.function.traffic.alt':'Situation on the road',
    'other.function.bus':'Bus',
    'other.function.bus.alt':'Bus',
    'other.function.tram': 'Tram',
    'other.function.tram.alt': 'Tram',
    'other.function.train': 'Train',
    'other.function.train.alt': 'Train',
    'product.description.text.clock.h1': 'With KoLiber you always know when your transport will arrive!',
    'product.description.text.clock.h3': 'Just a glimpse and you know how much time you have left',
    'product.description.text.calendar.h1':'Plan your trip!',
    'product.description.text.calendar.h3':'Plan your departure time and destination. Avoid disappointment.',
    'product.description.text.cloud.h1':'KoLiber will inform you about traffic.',
    'product.description.text.cloud.h3':'Real time service gives you actual information about present situation on the road',
    'contact.button.text':'Contact with us',
    'contact.form.h2':'Contact details:',
    'contact.form.logo':'KoLiber',
    'contact.form.description':'Kolibrowa 400c<br><br>80-999 Kolibrowo<br><br>Koliber Business Centre (10th floor)<br><br>tel. +48 999 999 999<br><br>email: biuro@koliber.pl',
    'contact.form.label':'Interested in our application?',
    'contact.form.label.small':'Contact us and we will inform you, when we are up and running!',
    'contact.telephone':'Telephone:',
    'contact.email':'Email address:',
    'contact.text':'Message:',
    'contact.text.placeholder':'Any suggestions? ',
    'aboutUs':'About us',
    //'contact.send':'Wyślij',
    'szymon1':'Traveler<br><br>',
    'szymon2':'Sailor<br><br>',
    'szymon3':'Backpacker<br><br>',
    'szymon4':'Receptive to world<br><br>',
    'szymon5':'Football fan<br><br>',
    'szymon6':'Technology geek<br><br>',
    'szymon7':'Indian cousine passioner<br><br>',
    'dominik1':'Always smiled<br><br>',
    'dominik2':'Agile follower<br><br>',
    'dominik3':'Likes challanges<br><br>',
    'dominik4':'Technology geek<br><br>',
    'dominik5':'Passionate about handball<br><br>',
    'dominik6':'Lover of freedom<br><br>',
    'dominik7':'Receptive to world and people<br><br>',
    'mateusz1':'Optimistic in life<br><br>',
    'mateusz2':'Runner<br><br>',
    'mateusz3':'Healthy perfectionist<br><br>',
    'mateusz4':'Planist<br><br>',
    'mateusz5':'Technology geek<br><br>',
    'mateusz6':'Amateur of maps<br><br>',
    'mateusz7':'Pilot<br><br>',
  },
  placeholders:{
    'form.email': 'name@domain.com',
    'form.text': 'Any suggestions? You want to pass your message? Leave your message here.'
  }
};